let posts = [
  {
    id: 1,
    media: [
      'https://zamin.uz/uploads/posts/2021-05/1620988120_jvi38ucg6vdqefvcig8xvjvx4jnhyomz_medium.jpg',
    ],
    desc: `Sadullaev Alisher , Temurbek Adhamov, Jakhongir Pulatov, Абдусаттор Абдураҳимов, Abdusamad Muminov kabi samimiy do'stlarimizga doim qo'llab-quvvatlaganliklari uchun tashakkur izhor qilamiz.`,
    seen: 2000,
    likes: 300,
    comment_count: 200,
    wishlist: false,
  },
  {
    id: 2,
    media: [
      '../videos/muhammadali1.mp4',
      'https://i.ytimg.com/vi/9GTiV9RE2L4/maxresdefault.jpg',
      'https://telegra.ph/file/bad6ae11079facbd4f757.jpg',
    ],
    desc: `Sadullaev Alisher , Temurbek Adhamov, Jakhongir Pulatov, Абдусаттор Абдураҳимов, Abdusamad Muminov kabi samimiy do'stlarimizga doim qo'llab-quvvatlaganliklari uchun tashakkur izhor qilamiz.`,
    seen: 600,
    likes: 700,
    comment_count: 600,
    wishlist: false,
  },
  {
    id: 3,
    media: [
      '../videos/muhammadali2.mp4',
      'https://i.ytimg.com/vi/gWGaQvcHG_g/hqdefault.jpg',
    ],
    images: ['https://i.ytimg.com/vi/atC4-noysVU/maxresdefault.jpg'],
    desc: `Ajrimlarning oldini olish uchun... \n #muhammadali_eshonqulov \n #patronlar_ligasi`,
    seen: 123000,
    likes: 7000,
    comment_count: 1005,
    wishlist: false,
  },
  {
    id: 4,
    media: [
      '../videos/muhammadali2.mp4',
      'https://i.ytimg.com/vi/gWGaQvcHG_g/hqdefault.jpg',
      'https://telegra.ph/file/bad6ae11079facbd4f757.jpg',
    ],
    desc: `Uylangan va uylanmagan insonning farqi katta`,
    seen: 12000,
    likes: 7030,
    comment_count: 1100,
    wishlist: false,
  },
  {
    id: 5,
    media: [
      '../videos/muhammadali1.mp4',
      'https://telegra.ph/file/bad6ae11079facbd4f757.jpg',
      '../videos/muhammadali2.mp4',
    ],
    desc: `shni 110% ga bajaring`,
    seen: 1201,
    likes: 70010,
    comment_count: 1306,
    wishlist: false,
  },
  {
    id: 6,
    media: ['../videos/muhammadali1.mp4'],
    desc: `@yuksalish_leaders_academy @yuksalish_chilonzor da bitiruv marosimiz`,
    seen: 101,
    likes: 710,
    comment_count: 106,
    wishlist: false,
  },
  {
    id: 7,
    media: ['../videos/muhammadali1.mp4'],
    desc: `@yuksalish_leaders_academy @yuksalish_chilonzor da bitiruv marosimiz`,
    seen: 101,
    likes: 710,
    comment_count: 106,
    wishlist: false,
  },
  {
    id: 8,
    media: ['https://telegra.ph/file/bad6ae11079facbd4f757.jpg'],
    desc: `@yuksalish_leaders_academy @yuksalish_chilonzor da bitiruv marosimiz`,
    seen: 101,
    likes: 710,
    comment_count: 106,
    wishlist: false,
  },
  {
    id: 9,
    media: [
      '../videos/muhammadali1.mp4',
      '../videos/muhammadali2.mp4',
      '../videos/muhammadali1.mp4',
    ],
    desc: `@yuksalish_leaders_academy @yuksalish_chilonzor da bitiruv marosimiz`,
    seen: 101,
    likes: 710,
    comment_count: 106,
    wishlist: false,
  },
];
